ALTER TABLE files ADD PRIMARY KEY (id);
CREATE INDEX CONCURRENTLY ON files (collection ASC NULLS LAST);
CREATE INDEX CONCURRENTLY ON files (path ASC NULLS LAST);
CREATE INDEX CONCURRENTLY ON files (last_modified ASC NULLS LAST);
CREATE INDEX CONCURRENTLY ON files (checksum_sha1 ASC NULLS LAST);
CREATE INDEX CONCURRENTLY ON files (agent ASC NULLS LAST);
