ALTER TABLE props ADD PRIMARY KEY (id);
CREATE INDEX CONCURRENTLY ON props (file_id ASC NULLS LAST);
CREATE INDEX CONCURRENTLY ON props (rel ASC NULLS LAST);
CREATE INDEX CONCURRENTLY ON props (obj ASC NULLS LAST);
CREATE INDEX CONCURRENTLY ON props (agent ASC NULLS LAST);

CREATE INDEX CONCURRENTLY ON props (file_id ASC NULLS LAST, rel ASC NULLS LAST);
CREATE INDEX CONCURRENTLY ON props (rel ASC NULLS LAST, obj ASC NULLS LAST);

CREATE INDEX CONCURRENTLY ON props (file_id, rel, obj);

CREATE INDEX CONCURRENTLY ON props(obj text_pattern_ops);
-- CREATE INDEX CONCURRENTLY ON props USING gist (obj gist_trgm_ops);

CREATE INDEX CONCURRENTLY ON props(rel text_pattern_ops);
CREATE INDEX CONCURRENTLY ON props(rel text_pattern_ops, obj text_pattern_ops);

ALTER TABLE props
ADD CONSTRAINT props_files FOREIGN KEY (file_id)
REFERENCES files (id) MATCH SIMPLE
ON UPDATE NO ACTION 
ON DELETE NO ACTION
DEFERRABLE
INITIALLY DEFERRED;